config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update]
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true,
            length: {minimum: 4}
  validates :email, presence: true
  validates :password, presence: true,
            length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<nav>
  <%= link_to "#{user.id}. #{user.username}, #{user.email}"%>
</nav>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<%= form_for(@user) do |f| %>

  <%= f.label :username %>:
  <%= f.text_field :username, class: 'form' %>

  <%= f.label :email %>:
  <%= f.email_field :email, class: 'form' %>

  <%= f.submit "Update", class: 'submit' %>

<% end %>

app/views/users/index.html.erb
<h1>All users</h1>
<%= render @users %>
<%= button_to("create new user", new_user_path, method: "get", class: 'submit') %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

  <%= f.label :username %>:
  <%= f.text_field :username, class: 'form' %>

  <%= f.label :email %>:
  <%= f.email_field :email, class: 'form' %>

  <%= f.label :password %>:
  <%= f.password_field :password, class: 'form' %>

  <%= f.submit "Create my account", class: 'submit' %>

<% end %>